name: Publish actions

on:
  push:
    branches:
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: pnpm/action-setup@v2
        with:
          version: '9'

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - run: npm run build

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions-bot"
          npx gh-pages --dist dist --branch latest
